Fix bug displaying default background on some devices
Some devices (e.g. onn google player) were not displaying the default
background with error:
 java.net.MalformedURLException: unknown protocol: android.resource
Changed to use resource ifg directly instead of via URL.